
CREATE TABLE ITALIA (NAZIONALE CHAR(4) PRIMARY KEY,
CATASTALE CHAR(4),
PROVINCIA CHAR(2),
COMUNE VARCHAR(50));

CREATE TABLE ESTERO (CONTINENTE CHAR(1),
SIGLA VARCHAR(3),
DENOMINAZ VARCHAR(50),
CODICE CHAR(4) PRIMARY KEY);

CREATE INDEX ITALIA01 ON ITALIA(COMUNE);
CREATE INDEX ITALIA02 ON ITALIA(PROVINCIA,COMUNE);
CREATE INDEX ESTERO01 ON ESTERO(DENOMINAZ);
